name: Nightly Data Refresh

on:
  schedule:
    - cron: "17 5 * * *"  # daily at 05:17 UTC
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Refresh data
        run: |
          python scripts/refresh_daily.py
