name: Wake Streamlit App

on:
  schedule:
    # every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium

      - name: Run wake script
        env:
          APP_URL: "https://hockeyshotmap-sparkerdata.streamlit.app/"
        run: |
          python .github/wake_streamlit.py
